name: itba-mlops-env
channels:
  - conda-forge
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - mlflow
    - dagster
    - dagster-webserver
    - dbt-postgres
    - scikit-learn
    - pandas
    - numpy
    - matplotlib
